language: cpp 
 
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      
before_install:
 - echo $DOCKER_PASS | docker login -u $DOCKER_ACC --password-stdin
 - docker pull pequimecanico/vsss-emc:latest


script:
  - docker build -t pequimecanico/vsss-emc:latest --cache-from="pequimecanico/vsss-emc:latest" .

after_success:
  - docker push pequimecanico/vsss-emc:latest
