version: "3.8"
services:
    workspace:
        image: pequi-vsss
        container_name: pequi-vsss-ws
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./:/root/src/
        environment:
            - "DISPLAY=:0"
    pequi:
        image: pequi-vsss
        container_name: pequi-vsss-run
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        environment:
            - "DISPLAY=:0"
        working_dir: /root/VSSS
        command: /root/VSSS/VSSS
    firasim_gui:
        image: pequi-vsss
        container_name: pequi-firasim
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        environment:
            - "DISPLAY=:0"
        working_dir: /root/FIRASim/bin
        command: /root/FIRASim/bin/FIRASim
    firasim_headless:
        image: pequi-vsss
        container_name: pequi-firasim-headless
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        environment:
            - "DISPLAY=:0"
        working_dir: /root/FIRASim/bin
        command: /root/FIRASim/bin/FIRASim --headless
    referee:
        image: pequi-vsss
        container_name: pequi-referee
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        environment:
            - "DISPLAY=:0"
        working_dir: /root/VSSReferee/bin
        command: /root/VSSReferee/bin/VSSReferee
