version: "3.8"
services:
  vsss:
    image: vsss
    container_name: vsss-emc
    stdin_open: true
    ipc: 'host'
    network_mode: "host"
    privileged: true
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      - "DISPLAY=:0"
    command: /VSSS
