version: "3.8"
services:
    workspace:
        image: pequi-vsss
        container_name: pequi-vsss-ws
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./:/root/src/
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
    pequi:
        image: pequi-vsss
        container_name: pequi-vsss-run
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./:/root/src/
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
        working_dir: /root/src
        command: bash -c "cd ./build && cmake .. && make -j$$(nproc) && cd .. && /root/src/VSSS"
    yellow_headless:
        image: pequi-vsss
        container_name: pequi-vsss-yellow-headless
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        build:
            context: .
            dockerfile: dockerfile
        working_dir: /root/VSSS
        command: /root/VSSS/VSSS yellow_headless.json
    blue_headless:
        image: pequi-vsss
        container_name: pequi-vsss-blue-headless
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        build:
            context: .
            dockerfile: dockerfile
        working_dir: /root/VSSS
        command: /root/VSSS/VSSS blue_headless.json
    firasim_gui:
        image: pequi-vsss
        container_name: pequi-firasim
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
        working_dir: /root/FIRASim/bin
        command: /root/FIRASim/bin/FIRASim
    firasim_headless:
        image: pequi-vsss
        container_name: pequi-firasim-headless
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
        working_dir: /root/FIRASim/bin
        command: /root/FIRASim/bin/FIRASim --headless
    referee:
        image: pequi-vsss
        container_name: pequi-referee
        stdin_open: true
        ipc: 'host'
        network_mode: "host"
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
        working_dir: /root/VSSReferee/bin
        command: /root/VSSReferee/bin/VSSReferee --3v3
